tonic-or-toxic/food/urls.py
from django.urls import path

from .views import (AddHarmfulProductView, AdditiveDetailsView, DashboardView,
                    HomepageView, LoginView, LogoutView,
                    SearchAdditivesByPhotoWizard, SearchAdditivesView,
                    SearchAdditiveView, ShowHarmfulProductsView, SignupView)

app_name = "food"
urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("search-additive/", SearchAdditiveView.as_view(), name="search_additive"),
    path("search-additives/", SearchAdditivesView.as_view(), name="search_additives"),
    path("additive-details/<int:additive_id>/",
         AdditiveDetailsView.as_view(),
         name="additive_details"),
    path("search-additives-by-photo/",
         SearchAdditivesByPhotoWizard.as_view(),
         name="search_additives_by_photo"),
    path("add-harmful-product/<str:toxicants_ids>/",
         AddHarmfulProductView.as_view(),
         name="add_harmful_product"),
    path("show-harmful-products/",
         ShowHarmfulProductsView.as_view(),
         name="show_harmful_products")
]

tonic-or-toxic/tonic_or_toxic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("food.urls", namespace='food'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tonic-or-toxic/food/models.py
from django.db import models


class ToxicantEN(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    medical_risks = models.CharField(max_length=100, blank=True)
    names = models.CharField(max_length=100, unique=True)


class ToxicantPL(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    medical_risks = models.CharField(max_length=100, blank=True)
    names = models.CharField(max_length=100, unique=True)


class Toxicant(models.Model):
    LOW = 'l'
    MODERATE = 'm'
    HIGH = 'h'
    VERY_HIGH = 'vh'
    TOXICANTS_SCALE = (
        (LOW, 'low'),
        (MODERATE, 'moderate'),
        (HIGH, 'high'),
        (VERY_HIGH, 'very high')
    )
    toxicant_en = models.OneToOneField(
        ToxicantEN, on_delete=models.CASCADE, null=True)
    toxicant_pl = models.OneToOneField(
        ToxicantPL, on_delete=models.CASCADE, null=True)
    scale = models.CharField(max_length=10, choices=TOXICANTS_SCALE)


class Product(models.Model):
    name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100, blank=True)
    toxicants = models.ManyToManyField(Toxicant)
    adding_date = models.DateField(auto_now_add=True)


class Image(models.Model):
    image = models.ImageField(upload_to='images/')

tonic-or-toxic/food/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Image, Product, Toxicant


def validate_email_unique(value):
    result = User.objects.filter(email=value).exists()
    if result:
        raise forms.ValidationError(
            f"Email address {value} already exists, must be unique!")


class SignupForm(UserCreationForm):
    email = forms.EmailField(validators=[validate_email_unique])

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)


class SelectLanguageForm(forms.Form):
    ENGLISH = "en"
    POLISH = "pl"
    LANGUAGES_CHOICES = (
        (ENGLISH, "English"),
        (POLISH, "Polish"))
    language = forms.ChoiceField(choices=LANGUAGES_CHOICES)


def validate_space_between_words(name):
    if " " in name.strip():
        if len(name.strip()) - len(name.strip().replace(" ", "")) != 1:
            raise forms.ValidationError(
                "Food additive name should have only one space between words!")


class SearchAdditiveForm(SelectLanguageForm):
    additive_name = forms.CharField(
        max_length=50,
        validators=[validate_space_between_words],
        error_messages={"required": "Food additive name cannot be an empty string!"})


def validate_comma_empty_name_space_between_words(names):
    if "," not in names:
        raise forms.ValidationError("Food additive names must be separated by commas!")
    for name in names.split(","):
        if len(name.strip()) == 0:
            raise forms.ValidationError("Food additive name cannot be an empty string!")
        validate_space_between_words(name)


class SearchAdditivesForm(SelectLanguageForm):
    additive_names = forms.CharField(
        max_length=2000,
        validators=[validate_comma_empty_name_space_between_words],
        error_messages={"required": "Food additive names cannot be an empty string!"})


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = "__all__"


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "manufacturer", "toxicants")

    def __init__(self, *args, **kwargs):
        toxicants_ids = kwargs.pop("toxicants_ids", None)
        super().__init__(*args, **kwargs)

        if toxicants_ids:
            self.fields["toxicants"].queryset = Toxicant.objects.filter(id__in=toxicants_ids)
            self.fields["toxicants"].initial = self.fields["toxicants"].queryset

tonic-or-toxic/food/views.py
import os
import re

import pytesseract
from PIL import Image
from formtools.wizard.views import SessionWizardView

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.core.files.storage.filesystem import FileSystemStorage
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from .forms import (ImageForm, LoginForm, ProductForm, SearchAdditiveForm,
                    SearchAdditivesForm, SelectLanguageForm, SignupForm)
from .models import Product, Toxicant


class HomepageView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("food:dashboard")
        else:
            return render(request, "homepage.html")


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "signup.html"
    success_url = reverse_lazy("food:login")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("food:dashboard")
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Congratulations!"
                         " Your signup is complete. You can now log in.")
        return response


class LoginView(View):
    form = LoginForm()
    html = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("food:dashboard")
        else:
            return render(request, self.html, {"form": self.form})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data["username"],
                                password=form.cleaned_data["password"])
            if user is not None:
                login(request, user)
                messages.success(request, "Congratulations!"
                                 " You have successfully logged in.")
                return redirect("food:dashboard")
            else:
                messages.error(request, "Invalid username or password!")
                return render(request, self.html, {"form": self.form})
        else:
            return render(request, self.html, {"form": self.form})


class LogoutView(LoginRequiredMixin, View):
    login_url = "food:login"

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect("food:homepage")


class DashboardView(LoginRequiredMixin, View):
    login_url = "food:login"

    def get(self, request, *args, **kwargs):
        return render(request, "dashboard.html")


def check_food_additives(request, language, food_additives):
    results = []
    if language == "en":
        for food_additive in food_additives:
            result = Toxicant.objects.filter(
                toxicant_en__names__icontains=food_additive.strip()).first()
            if result:
                results.append(result)
    elif language == "pl":
        for food_additive in food_additives:
            result = Toxicant.objects.filter(
                toxicant_pl__names__icontains=food_additive.strip()).first()
            if result:
                results.append(result)
    results_id = ",".join([str(tox.id) for tox in set(results)]) if results else ""
    return render(request, "results.html",
                  {"results": set(results), "results_id": results_id})


class SearchAdditiveView(LoginRequiredMixin, View):
    login_url = "food:login"
    form = SearchAdditiveForm()
    html = "search_additive.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.html, {"form": self.form})

    def post(self, request, *args, **kwargs):
        form = SearchAdditiveForm(request.POST)
        if form.is_valid():
            additive_name = []
            additive_name.append(form.cleaned_data["additive_name"])
            return check_food_additives(
                self.request, language=form.cleaned_data["language"],
                food_additives=additive_name)
        else:
            return render(request, self.html, {"form": form})


class SearchAdditivesView(SearchAdditiveView):
    form = SearchAdditivesForm()
    html = "search_additives.html"

    def post(self, request, *args, **kwargs):
        form = SearchAdditivesForm(request.POST)
        if form.is_valid():
            additive_names = form.cleaned_data["additive_names"].split(",")
            return check_food_additives(
                self.request, language=form.cleaned_data["language"],
                food_additives=additive_names)
        else:
            return render(request, self.html, {"form": form})


class AdditiveDetailsView(LoginRequiredMixin, View):
    login_url = "food:login"

    def get(self, request, additive_id):
        return render(request, "additive_details.html",
                      {"result": Toxicant.objects.get(pk=additive_id)})


class SearchAdditivesByPhotoWizard(LoginRequiredMixin, SessionWizardView):
    file_storage = FileSystemStorage(
        location=os.path.join(settings.MEDIA_ROOT, "wizard_upload"))
    login_url = "food:login"
    form_list = [SelectLanguageForm, ImageForm]

    def get_template_names(self):
        templates = ["search_additives_by_photo_1.html",
                     "search_additives_by_photo_2.html"]
        return [templates[int(self.steps.current)]]

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form, **kwargs)
        if self.steps.current == "1":
            cleaned_data = self.get_cleaned_data_for_step("0")
            language = cleaned_data["language"]
            context["language"] = language
        return context

    def done(self, form_list, *args, **kwargs):
        form_data = [form.cleaned_data for form in form_list]
        language = form_data[0]["language"]
        image_form = form_list[1]
        image = image_form.save()
        image_path = image.image.url.replace(
            settings.MEDIA_URL, settings.MEDIA_ROOT)

        with Image.open(image_path) as img:
            pillow_image_grey = img.convert("L")
            threshold = 128
            pillow_image_final = pillow_image_grey.point(
                lambda x: 0 if x < threshold else 255, "1")
            pillow_image_final.save(image_path)

        beginning_pattern_polish = r"(Sk[łtl]adniki[:\.S])"
        beginning_pattern_english = "Ingredients:"
        if language == "en":
            lang_rec = "eng"
            beginning_pattern = beginning_pattern_english
        else:
            lang_rec = "pol"
            beginning_pattern = beginning_pattern_polish
        recognized_text = pytesseract.image_to_string(
            image_path, lang=lang_rec, config="--psm 3")
        os.remove(image_path)
        image.delete()

        text_without_newline = recognized_text.replace("\n", " ")
        text_from_ingredients = re.split(
            beginning_pattern, text_without_newline)[-1]
        if text_from_ingredients[0] == text_without_newline:
            return render(self.request, "results.html",
                          {"message": "The image quality is low."
                           " Try again or capture a new photo"})
        text_prepared = text_from_ingredients.split(".")[0]
        additional_words_pattern = r"([a-ząćęłńóśźżA-ZĄĆĘŁÓŚŃŻŹ0-9- ]{3,}:)"
        text_only_additives = re.sub(
            additional_words_pattern, "", text_prepared)
        additives_pattern = r"[a-ząćęłńóśźżA-ZĄĆĘŁÓŚŃŻŹ0-9- ]{3,}"
        list_of_additives = re.findall(additives_pattern, text_only_additives)
        return check_food_additives(self.request, language=language,
                                    food_additives=list_of_additives)


class AddHarmfulProductView(LoginRequiredMixin,
                            PermissionRequiredMixin, CreateView):
    login_url = "food:login"
    permission_required = "food.add_product"
    form_class = ProductForm
    template_name = "add_product.html"
    success_url = reverse_lazy("food:show_harmful_products")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        toxicants_ids = self.kwargs.get("toxicants_ids")
        if toxicants_ids:
            toxicant_ids = [int(tox_id) for tox_id in toxicants_ids.split(",")]
            kwargs["toxicants_ids"] = toxicant_ids
        return kwargs

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Congratulations! You have successfully"
                                       " added the harmful product.")
        return response


class ShowHarmfulProductsView(LoginRequiredMixin,
                              PermissionRequiredMixin, View):
    login_url = "food:login"
    permission_required = "food.add_product"
    template_name = "show_harmful_products.html"

    def get(self, request, *args, **kwargs):
        return render(request, "show_harmful_products.html",
                      {"products": Product.objects.all()})

tonic-or-toxic/food/templates/add_product.html
{% extends "base.html" %}

{% block title %}
Add product
{% endblock title %}

{% block main %}
    <h1>Add product</h1>
  {% if form.errors %}
    <div class="message error">
      {% for field, errors in form.errors.items %}
        {% for error in errors %}
          {{ error }}<br>
        {% endfor %}
      {% endfor %}
    </div>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-control">
        {{ form.name.label_tag }}
        {{ form.name }}
    </div>
    <div class="form-control">
        {{ form.manufacturer.label_tag }}
        {{ form.manufacturer }}
    </div>
    <div class="form-control" style="display: none;">
        {{ form.toxicants.label_tag }}
        {{ form.toxicants }}
    </div>
    <div class="button-container centered">
        <button class="button-link" type="submit">Add</button>
    </div>
  </form>
{% endblock main %}

tonic-or-toxic/food/templates/additive_details.html
{% extends "base.html" %}

{% block title %}
Result
{% endblock title %}

{% block main %}
  {% if result %}
    <p><strong>Name:</strong> {{ result.toxicant_en.name }}</p>
    <p><strong>Description:</strong> {{ result.toxicant_en.description }}</p>
    <p><strong>Level of harmfulness:</strong> {{ result.get_scale_display }}</p>
    <p><strong>Medical risks:</strong> {{ result.toxicant_en.medical_risks }}</p>
  {% else %}
    <p>There is no harmful food additive like this in our database!</p>
  {% endif %}
    <div class="button-container centered">
      <a href="{% url 'food:dashboard' %}" class="button-link">Back to the dashboard</a>
    </div>
{% endblock main %}

tonic-or-toxic/food/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <header>
      <div class="left">
        <img src="{% static 'images/logo.jpg' %}" alt="Tonic or toxic">
      </div>
      <div class="right">
        {% if user.is_authenticated %}
          <a href="{% url 'food:logout' %}" class="button-link">Done?<br> It's time to log out!</a>
        {% else %}
          <a href="{% url 'food:signup' %}" class="button-link">First visit?<br> Let's get you signed up!</a>
          <a href="{% url 'food:login' %}" class="button-link">Missed us?<br> Let's get you logged in!</a>
        {% endif %}
      </div>
    </header>
        {% block main %}
        {% endblock main %}
    <footer>
      <div class="left">
        © 2024 by Const. All rights reserved
      </div>
      <div class="right">
        {% if user.is_authenticated %}
          Contact:   frolov.kostiantyn@gmail.com
        {% else %}
          Version 1.5
        {% endif %}
      </div>
    </footer>
  </body>
</html>

tonic-or-toxic/food/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
Dashboard
{% endblock title %}

{% block main %}
  {% if messages %}
    {% for message in messages %}
      <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}<br>
      </div>
    {% endfor %}
  {% endif %}
    <div class="button-container special">
      <a href="{% url 'food:search_additive' %}" class="button-link special">
          Concerned about food additive?<br>Search by name!</a>
      <a href="{% url 'food:search_additives' %}" class="button-link special">
          Checking several food additives?<br>Experience our multi-name search!</a>
      <a href="{% url 'food:search_additives_by_photo' %}" class="button-link special">
          Checking food additives by photo?<br>Explore our AI-driven solution!</a>
      {% if "food.add_product" in request.user.get_all_permissions %}
        <a href="{% url 'food:show_harmful_products' %}" class="button-link special">
            Adding harmful products?<br>View our collection of them!</a>
      {% endif %}
    </div>
    <p class="long-text">Our website's "Tonic or Toxic" rating system for harmful additives provides users
        with valuable insights into the safety of various ingredients. Utilizing a comprehensive
        approach, we base our ratings on a meticulous review of scientific evidence sourced from
        esteemed peer-reviewed literature, alongside data from authoritative entities like
        the U.S. Food and Drug Administration (FDA), the European Food Safety Authority (EFSA),
        and the World Health Organization (WHO). This thorough examination encompasses toxicological,
        epidemiological, and exposure data, ensuring a holistic understanding of each additive's
        potential impact on health. Additionally, we consider factors such as data reliability,
        uncertainties, and the additive's benefits, while also recognizing the unique
        vulnerabilities of certain groups, such as children or pregnant individuals. By synthesizing this
        wealth of information, our rating system aims to empower users to make informed choices about
        the substances they consume, promoting a healthier and safer lifestyle.</p>
{% endblock main %}

tonic-or-toxic/food/templates/homepage.html
{% extends "base.html" %}

{% block title %}
  Home page
{% endblock title %}

{% block main %}
  <h3>Do you prioritize the well-being of yourself and those you love?
      If so, this website offers valuable assistance!
  </h3>
    <p class="long-text">We explore the world of food additives. Food additives serve diverse functions, from preserving
            freshness to enhancing taste and texture. They come in various forms, ranging from single
            chemicals to complex mixtures, and can be of natural or synthetic origin. While many additives
            are harmless, some raise concerns about their potential health effects.
    </p>
    <p class="long-text">Our focus extends to the core of everyday products. From the fizz of soft drinks to the sweetness
            of packaged sweeteners, and from the indulgence of gelatin desserts to the convenience of frozen
            meals, additives permeate our food supply. Consider the subtle presence of additives in items like
            yogurt, candy, and chewing gum, where they play roles in texture and flavor enhancement. Even
            seemingly innocuous products like jams and fruit spreads may contain additives to prolong shelf life.
            Delve deeper into your pantry, and you'll find additives lurking in staples such as flour, bread, and
            condiments. Even beloved treats like chocolate and chips are not immune, often containing additives to
            achieve desired consistency or flavor. But it's not just about what's in our pantry. Additives also
            infiltrate restaurant fare, from pre-cooked meats to fried delicacies. Even seemingly healthy options
            like salad dressings and coffee creamers may contain additives that raise eyebrows.
    </p>
    <p class="long-text">Yet, amid these concerns, there's room for informed decision-making. By understanding the role of
            additives and their potential impacts, we empower ourselves to make choices that prioritize health
            and wellness. Join us as we navigate this complex landscape, shedding light on the additives that
            shape our food and empowering you to make choices that align with your values and well-being!
    </p>
{% endblock main %}

tonic-or-toxic/food/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock title %}

{% block main %}
  <h1>Login</h1>
  {% if messages %}
    {% for message in messages %}
      <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}<br>
      </div>
    {% endfor %}
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-control">
      {{ form.username.label_tag }}
      {{ form.username }}
    </div>
    <div class="form-control">
      {{ form.password.label_tag }}
      {{ form.password }}
    </div>
    <div class="button-container centered">
        <button class="button-link" type="submit">Login</button>
    </div>
  </form>
{% endblock main %}

tonic-or-toxic/food/templates/result.html
{% extends "base.html" %}

{% block title %}
Result
{% endblock title %}

{% block main %}
  {% if result %}
    <p><strong>Name:</strong> {{ result.toxicant_en.name }}</p>
    <p><strong>Description:</strong> {{ result.toxicant_en.description }}</p>
    <p><strong>Level of harmfulness:</strong> {{ result.get_scale_display }}</p>
    <p><strong>Medical risks:</strong> {{ result.toxicant_en.medical_risks }}</p>
  {% else %}
    <p>There is no harmful food additive like this in our database!</p>
  {% endif %}
    <div class="button-container centered">
      <a href="{% url 'food:dashboard' %}" class="button-link">Back to the dashboard</a>
    </div>
{% endblock main %}

tonic-or-toxic/food/templates/results.html
{% extends "base.html" %}

{% block title %}
Results
{% endblock title %}

{% block main %}
  {% if message %}
    <p>{{ message }}</p>
  {% else %}
    {% if results %}
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Level of harmfulness</th>
            <th>More info</th>
          </tr>
        </thead>
        <tbody>
          {% for result in results %}
            <tr>
              <td>{{ result.toxicant_en.name }}</td>
              <td>{{ result.get_scale_display }}</td>
              <td><a href="{% url 'food:additive_details' result.id %}">See details</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>There is no harmful food additives like this in our database!</p>
    {% endif %}
    {% if results and "food.add_product" in request.user.get_all_permissions %}
      <div class="button-container centered">
        <a href="{% url 'food:add_harmful_product' results_id  %}" class="button-link">
          Add to the list of harmful products</a>
      </div>
    {% endif %}
    <div class="button-container centered">
      <a href="{% url 'food:dashboard' %}" class="button-link">Back to the dashboard</a>
    </div>
  {% endif %}
{% endblock main %}

tonic-or-toxic/food/templates/search_additive.html
{% extends "base.html" %}

{% block title %}
Search additive
{% endblock title %}

{% block main %}
  {% if form.additive_name.errors %}
    <div class="message error">
      {% for error in form.additive_name.errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-control">
      {{ form.additive_name.label_tag }}
      {{ form.additive_name }}
      <div class="help-text">Please enter or paste
        the name of the food additive you wish to check<br>
        If a name consists of two or more words, use only one space between them
      </div>
    </div>
    <div class="form-control select">
        {{ form.language.label_tag }}
        {{ form.language }}
        <div class="help-text">Please choose the language
            for the name of the food additive</div>
    </div>
    <div class="button-container centered">
        <button class="button-link" type="submit">Search</button>
    </div>
  </form>
{% endblock main %}

tonic-or-toxic/food/templates/search_additives.html
{% extends "base.html" %}

{% block title %}
Search additives
{% endblock title %}

{% block main %}
  {% if form.additive_names.errors %}
    <div class="message error">
      {% for error in form.additive_names.errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-control">
      {{ form.additive_names.label_tag }}
      {{ form.additive_names }}
      <div class="help-text">Please enter or paste the names of at least
            two food additives separated by comma that you wish to check<br>
          If a name consists of two or more words, use only one space between them
      </div>
    </div>
    <div class="form-control select">
      {{ form.language.label_tag }}
      {{ form.language }}
      <div class="help-text">Please choose the language
            for the names of the food additives
      </div>
    </div>
    <div class="button-container centered">
      <button class="button-link" type="submit">Search</button>
    </div>
  </form>
{% endblock main %}

tonic-or-toxic/food/templates/search_additives_by_photo_1.html
{% extends "base.html" %}

{% block title %}
Search additives by photo
{% endblock title %}

{% block main %}
  <h1>Step 1 - Select a language</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ wizard.management_form }}
        <div class="form-control select">
          {{ wizard.form.language.label_tag }}
          {{ wizard.form.language }}
          <div class="help-text">Please choose the language
            for the text representing the food additives
          </div>
        </div>
        <div class="button-container centered">
          <button class='button-link' type="submit">Next</button>
        </div>
    </form>
{% endblock main %}

tonic-or-toxic/food/templates/search_additives_by_photo_2.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Search additives by photo
{% endblock title %}

{% block main %}
  <h1>Step 2 - Upload a photo</h1>
    <p>The quality of your image will have a crucial impact on the result!
        When capturing a photo, follow the tips provided below.</p>
    <ul>
      <li>Make sure to capture the complete list of food ingredients</li>
      <li>For optimal horizontal text capture, utilize grid lines</li>
      <li>Follow device suggestions</li>
      <li>Refrain from using flash</li>
      <li>Trim the image to remove any unnecessary elements</li>
      <li>If your device allows, aim for a photo resolution of approximately 200 pixels per inch (ppi)</li>
    </ul>
    <p>For reference, please see the example provided below.</p>
    {% if language == "en" %}
      <div class="example">
        <img src="{% static 'images/example_en.jpg' %}" alt="Example of photo">
      </div>
    {% else %}
      <div class="example">
        <img src="{% static 'images/example_pl.jpg' %}" alt="Example of photo">
      </div>
    {% endif %}
    <p>After capturing the photo, proceed to upload it.</p>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
        {{ wizard.management_form }}
          <div class="form-control select">
            {{ wizard.form.image.label_tag }}
            {{ wizard.form.image }}
          </div>
      <div class="button-container centered">
        <button class="button-link" type="submit">Next</button>
      </div>
    </form>
{% endblock main %}

tonic-or-toxic/food/templates/show_harmful_products.html
{% extends "base.html" %}

{% block title %}
Harmful products
{% endblock title %}

{% block main %}
  {% if messages %}
    {% for message in messages %}
      <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}<br>
      </div>
    {% endfor %}
  {% endif %}
  {% if products %}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Manufacturer</th>
          <th>Adding date</th>
          <th>Harmful additives</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
          <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.manufacturer }}</td>
            <td>{{ product.adding_date }}</td>
            <td>{% for toxicant in product.toxicants.all %}
                <a href="{% url 'food:additive_details' toxicant.id %}">
                {{ toxicant.toxicant_en.name }}</a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There is no harmful products in our database!</p>
  {% endif %}
  <div class="button-container centered">
    <a href="{% url 'food:dashboard' %}" class="button-link">Back to the dashboard</a>
  </div>
{% endblock main %}